articles/urls.py
from django.conf import settings
from django.urls import path

from .views import ArticleListView, ArticleDetailView, articles_of_category
app_name = 'articles'
urlpatterns = [

    path('', ArticleListView.as_view(), name="articles_list"),
    path('<int:pk>/', ArticleDetailView.as_view(), name="article_detail"),
    path('category/<int:pk>/', articles_of_category, name="articles_category")
    # path('ckeditor/', include('ckeditor_uploader.urls')),
]

raey/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from django.contrib.sitemaps.views import sitemap
from .sitemap import StaticViewSitemap, ArticleSitemap, CategorySitemap

from django.views.generic import TemplateView, RedirectView

from .views import AdsView
from articles.views import index

sitemaps = {
    'static': StaticViewSitemap,
    'categories': CategorySitemap,
    'articles': ArticleSitemap,
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type='text/plain')),
    path('^favicon.ico', RedirectView.as_view(
        url='/static/img/favicon.ico')),
    path('ads.txt', AdsView.as_view()),
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('articles/', include('articles.urls', namespace='articles')),
    path('forms/', include('survey.urls', namespace='survey'))

    # path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load humanize %}
{% load l10n %}

{% load compress %}
{% load meta %}

{%load extra_tags %}

<!doctype html>
<html>

<head {% meta_namespaces %}>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" sizes="16x16" type="image/png">
    {% include "meta/meta.html" %}

    <link href="https://fonts.googleapis.com/css?family=Cairo|Tajawal&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/rtl/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endcompress %}

    <!-- Google Adsense -->
    <script data-ad-client="ca-pub-8503106498493880" async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    {% block extra_assets %}

    {% endblock extra_assets %}

    <title>جريدة الرائى - {% block title %} آخر عدد{% endblock title %}</title>

</head>

<body>
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>
    {% with request.resolver_match.url_name as url_name %}
    <div id="fb-root">
    </div>
    <script async defer crossorigin="anonymous"
        src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v5.0"></script>

    <nav class="nav bg-dark shadow justify-content-between px-md-3">

        <div class="" id="social-icons">
            <a href="" target="blank">
                <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="https://www.youtube.com/user/Elra2yTube" target="blank">
                <i class="fa fa-youtube" aria-hidden="true"></i>
            </a>
            <a href="https://www.facebook.com/khdmtelrayy/" target="blank">
                <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
        </div>

        <div class="text-white-50">
            العدد {{last_issue.name}}
            <!-- - {{ last_issue.pub_date|date:'F  Y'|localize}} -->
        </div>

    </nav>

    <div class="logo my-1">
        <a href="{% url 'index' %}" class="text-decoration-none">
            <img src="{% static 'img/logo.png' %}" alt="" height="150" class="d-block mx-auto">
        </a>
        <p class="text-center">ثُمَّ رَأَيْتُ سَمَاءً جَدِيدَةً وَأَرْضًا جَدِيدَةً، لأَنَّ السَّمَاءَ الأُولَى
            وَالأَرْضَ الأُولَى مَضَتَا،
            وَالْبَحْرُ لاَ يُوجَدُ فِي مَا بَعْدُ. (رؤ 21: 1)</p>

    </div>
    <header class="header-sticky">
        <nav class="navbar navbar-light navbar-expand-lg d-flex flex-row-reverse shadow-lg px-5 py-lg-0" id="main-nav">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            {% if url_name != 'index' %}
            <a href="/" class="d-block d-md-none btn " style="background-color:#f78d73">
                الرجوع الى الرئيسية
                <img class="d-inline" src="{% static 'img/home_icon.png' %}" alt="">
            </a>
            {% endif %}

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto flex-lg-row-reverse">
                    <li class="nav-item">
                        <a class="nav-link {% if url_name == 'index' %} active {% endif %}" href="{% url 'index' %}">
                            آخر عدد <i class="fa fa-newspaper-o" aria-hidden="true"></i></a>
                    </li>
                    {% for category in categories %}

                    <li class="nav-item">
                        {% with category.pk as pk%}

                        <a class="nav-link {% if request.path == pk|getcat %} active {% endif %}"
                            href="{% url 'articles:articles_category' category.pk %}">{{category.name}} </a>
                        {% endwith %}
                    </li>

                    {% endfor %}
                </ul>
            </div>
        </nav>
    </header>

    <div class="container-fluid my-4">

        <div class="row d-md-flex flex-md-row-reverse main-news-card align-items-md-center">
            {% block main_news %}

            {% endblock main_news %}
        </div>

    </div>

    <div class="container-fluid my-4">
        <div class="row d-flex flex-row-reverse mx-auto">
            {% if url_name == 'index' %}
            <div class="col-sm-12 col-md-3 order-md-1">
                {% block article %}

                {% endblock article %}
            </div>
            {% endif %}

            <div class="col-sm-12 {% if url_name == 'index' %}col-md-7{% else %}col-md-9{% endif %} order-md-0">
                {% block content %}

                {% endblock content %}
            </div>

            <div class="col-sm-12 col-md-2 order-md-2 d-none d-sm-block ml-md-auto">
                <!-- <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                             
                                <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8503106498493880" data-ad-slot="8354980434"
                                    data-ad-format="auto" data-full-width-responsive="true"></ins>
                                <script>
                                    (adsbygoogle = window.adsbygoogle || []).push({});
                                </script> -->
                <img src="{% static 'img/put_ads.png' %}" alt="" width="200">
                <img src="{% static 'img/put_ads.png' %}" alt="" width="200">
                <img src="{% static 'img/put_ads.png' %}" alt="" width="200">
                <img src="{% static 'img/put_ads.png' %}" alt="" width="200">
                <img src="{% static 'img/put_ads.png' %}" alt="" width="200">
                <img src="{% static 'img/put_ads.png' %}" alt="" width="200">
            </div>

        </div>

    </div>


    <a id="button"></a>


    <footer id="main-footer" class="container-fluid bg-dark text-white">

        <div class="row">
            <div class="col text-center">
                <p class=""> جميع الحقوق محفوظة &copy;2011 - <span id="year"></span>- جريدة الرائــى
            </div>
        </div>
    </footer>
    {% endwith %}


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"
        integrity="sha384-a9xOd0rz8w0J8zqj1qJic7GPFfyMfoiuDjC9rqXlVOcGO/dmRqzMn34gZYDTel8k"
        crossorigin="anonymous"></script>

    {% compress js %}
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% endcompress %}

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-133683028-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-133683028-2');
    </script>

</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load cropping %}

{% block main_news %}

<div class="col-sm-12 col-md-6 order-1">
    {% for n in news %}
        {% if forloop.first %}
        <div class="row pb-3">
            {% endif %}
            <div class="col-6">
                <a href="{% url 'articles:article_detail' n.pk %}">
                    <div class="card shadow text-black">
                        <img class="card-img img-fluid" src="{% cropped_thumbnail n 'cropping' %}" alt="{{n.title}}" style="max-height:205px;">
                        <div class="card-img-overlay">
                            <p class="card-text font-weight-bolder shadow">{{n.title}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% if forloop.last %}
    </div>
</div>
<div class="col-sm-12 col-md-6 order-0">
    <div class="card shadow text-black">
        <a href="{% url 'articles:article_detail' m.pk %}">
            <img class="card-img img-fluid" src="{% cropped_thumbnail m 'cropping' %}" alt="Card image">
            <div class="card-img-overlay">
                <p class="card-text font-weight-bolder">{{m.title}}</p>
            </div>
        </a>
    </div>
</div>
{% endif %}

{% if forloop.counter|divisibleby:2 %}
    </div>
    <div class="row">
        {% endif %}

        {% endfor %}
        {% endblock main_news %}


        {% block content %}

        {% if reports %}
        <div class="row">
            <div class="col-sm-12 order-1 card shadow">
                <div class="card-label shadow-lg rounded">
                    <img src="{% static 'img/logo.png' %}" alt="" width="70">
                    <span class="text-black">تقارير </span>
                </div>
                <div class="card-body mt-5">
                    <div class="row">

                        <div class="owl-carousel owl-theme">
                            {% for q in reports %}
                            <div class="item">

                                <a href="{% url 'articles:article_detail' q.pk %}" class="card-link">

                                    <div class="card">
                                        <img class="card-img-top img-fluid" src="{% cropped_thumbnail q 'cropping' %}" alt="{{q.title}}"
                                            style="max-height:150px;">
                                        <div class="card-body card-hover">
                                            <p class="card-text">{{q.title}}</p>

                                        </div>
                                    </div>
                                </a>

                            </div>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
{% endif %}

    {% if investigations %}
    <div class="row my-5">
        <div class="col-sm-12 order-1 card shadow">
            <div class="card-label shadow-lg rounded">
                <img src="{% static 'img/logo.png' %}" alt="" width="70">
                <span class="text-black">تحقيقات </span>
            </div>
            <div class="card-body mt-5">
                <div class="row">

                    <div class="owl-carousel owl-theme">
                        {% for q in investigations %}
                        <div class="item">

                            <a href="{% url 'articles:article_detail' q.pk %}" class="card-link">

                                <div class="card">
                                    <img class="card-img-top img-fluid" src="{% cropped_thumbnail q 'cropping' %}" alt="{{q.title}}"
                                        style="max-height:150px;">
                                    <div class="card-body card-hover">
                                        <p class="card-text">{{q.title}}</p>

                                    </div>
                                </div>
                            </a>

                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {% if spirtuals %}
    <div class="row my-5">
        <div class="col-sm-12 order-1 card shadow">
            <div class="card-label shadow-lg rounded">
                <img src="{% static 'img/logo.png' %}" alt="" width="70">
                <span class="text-black">روحيات </span>
            </div>
            <div class="card-body mt-5">
                <div class="row">
                    <div class="owl-carousel owl-theme">
                        {% for q in spirtuals %}
                        <div class="item" s>

                            <a href="{% url 'articles:article_detail' q.pk %}" class="card-link">

                                <div class="card">
                                    <img class="card-img-top img-fluid" src="{% cropped_thumbnail q 'cropping' %}" alt="{{q.title}}">
                                    <div class="card-body card-hover">
                                        <p class="card-text">{{q.title}}</p>

                                    </div>
                                </div>
                            </a>

                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endif %}

    {% if articles %}
    <div class="row my-5">
        <div class="col-sm-12 order-1 card shadow">
            <div class="card-label shadow-lg rounded">
                <img src="{% static 'img/logo.png' %}" alt="" width="70">
                <span class="text-black">مقالات </span>
            </div>
            <div class="card-body mt-5">
                <div class="row">

                    <div class="owl-carousel owl-theme">
                        {% for q in articles %}
                        <div class="item">

                            <a href="{% url 'articles:article_detail' q.pk %}" class="card-link">

                                <div class="card">
                                    <img class="card-img-top img-fluid" src="{% cropped_thumbnail q 'cropping' %}" alt="{{q.title}}"
                                        style="max-height:150px;">
                                    <div class="card-body card-hover">
                                        <p class="card-text">{{q.title}}</p>

                                    </div>
                                </div>
                            </a>

                        </div>

                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endif %}


    {% endblock content %}

    {% block article %}

    {% if main_article %}
    <div class="card shadow" id="main-article">
        <a href="{% url 'articles:article_detail' main_article.pk %}">
            {% if author_article.image.url != None %}
            <img src="{% cropped_thumbnail author_article 'cropping' %}" alt="" width="50%" class="d-block mx-auto">
            {% endif %}
            <p class="h5 text-center "> : {{author_article.name}} يكتب </h4>
            <p class="h4 text-center"> {{main_article.title}} </p>

        </a>


    </div>
    {% endif %}

   
    <div class="col-12 p-4">
        <a href="{{MEDIA_URL}} {{main_article.pdf_file}}">
            <img src="{% static 'img/download_pdf.png' %}" alt="" class="img-fluid rounded">
        </a>
    </div>
    

    {% if reportage %}
    <div class="row p-md-4 mb-5">
        <div class="col-sm-12 card shadow">
            <div class="card-label rounded">
                <img src="{% static 'img/logo.png' %}" alt="" width="70">
                <span class="text-black">حوار </span>
            </div>
            <div class="card-body mt-5">
                <div class="row">

                    <div class="col-12 mb-2">

                        <a href="{% url 'articles:article_detail' reportage.pk %}" class="card-link">

                            <div class="card">
                                <img class="card-img-top" src="
                                                {% if reportage.image.url != None %}
                                                    {% cropped_thumbnail reportage 'cropping' %}
                                                {% endif %}
                                                    " alt="{{reportage.title}}" style="max-height:150px;">
                                <div class="card-body card-hover">
                                    <p class="card-text">{{reportage.title}}</p>

                                </div>
                            </div>
                        </a>

                    </div>

                </div>


            </div>
        </div>

    </div>
    {% endif %}

    
    <div class="col-sm-12 mx-auto p-4 d-none d-md-block">
        <div class="fb-page" data-href="https://www.facebook.com/elra2ynews/" data-tabs="timeline" data-width="" data-height=""
            data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
            <blockquote cite="https://www.facebook.com/elra2ynews/" class="fb-xfbml-parse-ignore"><a
                    href="https://www.facebook.com/elra2ynews/">‎بوابة الرائي للاخبار الكنسية‎</a></blockquote>
        </div>
    </div>
    

    {% endblock article %}